version: '3.8'
services:
  discord-bot:
    build: 
        context: .
        dockerfile: ArmaforcesMissionBot/Dockerfile
    ports:
      - "5005:80"
      - "443:443"
    env_file: .env
    restart: unless-stopped
    environment:
        TZ: "Europe/Warsaw"
  